[project]
name = "Simple-Tiled-Implementation"
version = "1.2.3.0"
description = "Tiled library for LÃ–VE"
author = "Landon Manning"
license = "MIT"

[environment]
type = "LOVE"
src_dir = "sti"

[dependencies]