[project]
name = "Simple-Tiled-Implementation"
version = "632bc89"
description = "Love2D screen-scaling library, single Lua file"
author = "Challacade LLC"
license = "MIT"

[environment]
type = "LOVE"
src_dir = "."

[dependencies]